// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIbXZB2ncEnPryrcKoHtWyVj7vZiXPpqo',
    appId: '1:1056411112452:web:d54cc71bec40cb8720d151',
    messagingSenderId: '1056411112452',
    projectId: 'sikep-temporary-db',
    authDomain: 'sikep-temporary-db.firebaseapp.com',
    storageBucket: 'sikep-temporary-db.firebasestorage.app',
    measurementId: 'G-CEG40HX3BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-sy4tMgBLSz8xzNTg-YxSR341uUgu1V4',
    appId: '1:1056411112452:android:583370ef2c3587f920d151',
    messagingSenderId: '1056411112452',
    projectId: 'sikep-temporary-db',
    storageBucket: 'sikep-temporary-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdNs7RpMVDSFTyQUCuKUb8pUit9cFpUec',
    appId: '1:1056411112452:ios:6dfc114e0b5a65d920d151',
    messagingSenderId: '1056411112452',
    projectId: 'sikep-temporary-db',
    storageBucket: 'sikep-temporary-db.firebasestorage.app',
    iosBundleId: 'com.example.sikep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdNs7RpMVDSFTyQUCuKUb8pUit9cFpUec',
    appId: '1:1056411112452:ios:6dfc114e0b5a65d920d151',
    messagingSenderId: '1056411112452',
    projectId: 'sikep-temporary-db',
    storageBucket: 'sikep-temporary-db.firebasestorage.app',
    iosBundleId: 'com.example.sikep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIbXZB2ncEnPryrcKoHtWyVj7vZiXPpqo',
    appId: '1:1056411112452:web:5548fdba678d84d720d151',
    messagingSenderId: '1056411112452',
    projectId: 'sikep-temporary-db',
    authDomain: 'sikep-temporary-db.firebaseapp.com',
    storageBucket: 'sikep-temporary-db.firebasestorage.app',
    measurementId: 'G-V9T19Y8ZZY',
  );
}
